name: Update Changelog
on:
  push:
    branches : [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update Changelog
        run:  bash ./update_changelog.sh

      - name: Commit the changes in the Changelog to master
        run: |
          git add ./CHANGELOG.md
          git commit -m "Automatic update of changelog."
      
      - name: Push the commit to master branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          force: true