name: Update Changelog
on:
  push:
    branches : [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update Changelog
        run:  bash ./update_changelog.sh